testDjango/blog/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from django.contrib import admin
import blog.views as v

urlpatterns = [
    url(r'^index/$', v.hello),  # 使用正则表达式开始符号和结束符号连起来写表示空，
    # 若使用此种方式，若是匹配地址就必须向index/，因为地址访问时会自动加一个/
    url(r'^article/(?P<id>[0-9]+)$', v.article_page, name='article_page'),
    url(r'^edit/(?P<id>[0-9]+)$', v.edit_page, name='edit_page'),
    url(r'^edit/action$', v.edit_action, name='edit_action'),
    url(r'^posttest/$',v.posttest,name = 'posttest'),
]

testDjango/blog2/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django.conf.urls import url,include
from django.contrib import admin
from blog2.views import hello
urlpatterns = [
    url(r'^index/$',hello) #使用正则表达式开始符号和结束符号连起来写表示空，
                        # 若使用此种方式，若是匹配地址就必须向index/，因为地址访问时会自动加一个/
]

testDjango/testDjango/urls.py
from django.conf.urls import url,include
from django.contrib import admin
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'blog/',include('blog.urls',namespace='blog')),
    url(r'blog2/',include('blog2.urls'))
]

testDjango/blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=32, default="Title")
    content = models.TextField(null=True)
    pub_time = models.DateTimeField(auto_now=True)
    def __unicode__(self):
        return self.title

testDjango/blog2/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

testDjango/blog/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render
from django.http import HttpResponse
import models


# Create your views here.
def hello(request):
    articals = models.Article.objects.all()
    return render(request, "blog/index.html", {"articals": articals})


def article_page(request, id):
    article = models.Article.objects.get(pk=id)
    return render(request, 'blog/article_page.html', {"article": article})


def edit_page(request, id):
    if str(id) == '0':
        return render(request, 'blog/edit_page.html')
    else:
        art = models.Article.objects.get(pk=id)
        return render(request, 'blog/edit_page.html', {'article': art})


def edit_action(request):
    id = request.POST.get('id', '0')
    title = request.POST.get("title", "TITLE")
    content = request.POST.get('content', 'CONTENT')
    if str(id) == '0':
        models.Article.objects.create(title=title, content=content)
        articles = models.Article.objects.all()
        return render(request, 'blog/index.html', {'articals': articles})

    else:
        article = models.Article.objects.get(pk=id)
        article.title = title
        article.content = content
        article.save()
        return render(request, 'blog/article_page.html', {'article': article})


def posttest(request):
    name = request.POST.get("name")
    pwd = request.POST.get("pass")
    print name
    return render(request, 'blog/posttest.html', {"name": name, "pass": pwd})

testDjango/blog2/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.
def hello(request):
    return render(request, "blog2/index.html")

testDjango/blog/templates/blog/article_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Article Page</title>
</head>
<body>
<h1>{{ article.title }}</h1>
<br/>
<h3>{{ article.content }}</h3>
<br/><br/>
<a href="{% url 'blog:edit_page' article.id %}">修改文章</a>
</body>
</html>

testDjango/blog/templates/blog/edit_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit Page</title>
</head>
<body>
<form action="{% url 'blog:edit_action' %}" method="post">
    {% csrf_token %}
        <input type="hidden" name="id" value="{{ article.id | default:'0'}}">
        <label>文章标题
            <input type="text" name="title" value="{{ article.title }}">
        </label>
        <br/>
        <label>文章内容
            <input type="text" name="content" value="{{ article.content }}">
        </label>
        <input type="submit" value="提交">
</form>
</body>
</html>

testDjango/blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>
    <a href="{% url 'blog:edit_page' '0'%}">新文章</a>
</h1>
{% for article in articals %}
    <a href="{% url 'blog:article_page' article.id %}">{{ article.title }}</a>
    <br>
{% endfor %}
</body>
</html>

testDjango/blog/templates/blog/posttest.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>post test</title>
</head>
<body>
<form action="{% url 'blog:posttest' %}" method="post">
    {% csrf_token %}
    <label>用户名
        <input name="name" type="text">
    </label>
    <br>
    <label>密码
        <input type="password" name="pass">
    </label>
    <br>
    <input type="submit" value="登陆">
</form>
<h1>用户名:{{ name }}</h1><br>
<h1>密码：{{ pass }}</h1>
</body>
</html>

testDjango/blog2/templates/blog2/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>hello blog2222</h1>
</body>
</html>